### ISSUE TITLE
Cannot find any supported version doc for css plugin

### ISSUE THREAD

**Issue by hgc2002** [SonarQubeCommunity/sonar-css#149]
I've been looking for which versions of sonar are supported by what css plugin.

Is there any place where this is documented?

I'm particulary interested in which LTS versions of SQ are supported by what css plugin versions.

Thanks for your help.

Regards,
Herman.

**Comment by racodond** [comment]
Hi Herman,

Here's the page you're looking for:http://docs.sonarqube.org/pages/viewpage.action?pageId=1442127

Regards,

David

**Comment by racodond** [comment]
README file updated with the link to the plugin version matrix.
