### ISSUE TITLE
Links in README.md are incorrect since rename of GitHub repo was renamed

### ISSUE THREAD

**Issue by gjsjohnmurray** [SonarQubeCommunity/sonar-css#157]
Still pointing to SonarCommunity, which no longer redirects and seems to have been acquired by someone else.

**Comment by racodond** [comment]
Thanks @gjsjohnmurray for your feedback!
This is now fixed by https://github.com/SonarQubeCommunity/sonar-css/commit/02c90cc580469587ccbccb08cc1708897ad93a30
