### ISSUE TITLE
NPE Formatting rule on ruleset without any selector

### ISSUE THREAD

**Issue by racodond** [SonarQubeCommunity/sonar-css#160]
See https://groups.google.com/d/msg/sonarqube/T9-IJRDrSdA/nGIBSP3qBQAJ

**Comment by racodond** [comment]
Fixed in https://github.com/SonarQubeCommunity/sonar-css/commit/a04118a97a58935d0438d99422003c4439a0b63d

**Comment by ganncamp** [comment]
Hi. When will this be released?

**Comment by racodond** [comment]
I'll proceed with the release next week.
