### ISSUE TITLE
Update compatibility matrix for 1.10 and SonarQube 5.2+

### ISSUE THREAD

**Issue by fabdouglas** [SonarQubeCommunity/sonar-css#255]
CSS 1.10 is compatible to 5.2+, but compatibility matrix has not been updated :
http://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix

So using this version with a SonarQube 5.1 is allowed from plugin manager but gives this error :
`Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.sonar.plugins.css.CssSquidSensor has unsatisfied dependency 'class org.sonar.css.ast.visitors.SonarComponents' for constructor 'public org.sonar.plugins.css.CssSquidSensor(org.sonar.css.ast.visitors.SonarComponents,org.sonar.api.batch.fs.FileSystem,org.sonar.api.batch.rule.CheckFactory,org.sonar.api.issue.NoSonarFilter)' from org.picocontainer.DefaultPicoContainer@56a260cf:352<[Immutable]:org.picocontainer.DefaultPicoContainer@520b17f1:305<[Immutable]:org.picocontainer.DefaultPicoContainer@5b1d09dd:20<[Immutable]:org.picocontainer.DefaultPicoContainer@bfbb5ac:116<|`

**Comment by racodond** [comment]
Thanks a lot for your feedback @fabdouglas! I just asked SonarSource to update both the page and the Update Center.
