### ISSUE TITLE
when I scan those postCSS,I got error: Unable to parse file: color.css

### ISSUE THREAD

**Issue by chanjetsdp** [SonarQubeCommunity/sonar-css#275]
10:21:36.644 ERROR - Unable to parse file: /xxx/src/css/common/color.css
10:21:36.644 ERROR - Parse error at line 7 column 1:

 1: /**
 2:  * Created with WebStorm.
 3:  * User: xxx
 4:  * Date: 16-2-12
 5:  * common colors
 6:  */
 7: $blue : #3ec8dd;
    ^
 8: $blueDuck : #18a9bf;
 9: $blueActive : #37b1c4;
10: $green : #93d200;
11: $greenActive : #81b800;
12: $yellow : #e7e53e;
13: $orange : #ffa100;
14: $orangeActive : #e59100;
15: $red : #f56058;
16: $redActive : #d63f37;
17: $red2 : #7c3c3c;

**Comment by chanjetsdp** [comment]
color.css 

/**
 * Created with WebStorm.
 * User: xxx
 * Date: 16-2-12
 *  common colors
 */
$blue : #3ec8dd;
$blueDuck : #18a9bf;
$blueActive : #37b1c4;
$green : #93d200;
$greenActive : #81b800;
$yellow : #e7e53e;
$orange : #ffa100;
$orangeActive : #e59100;
$red : #f56058;
$redActive : #d63f37;
$red2 : #7c3c3c;
$light-grey: #EDEDED;
$white: #ffffff;
$black: #000000;

$gray1 : #333333;
$gray2 : #666666;
$gray3 : #999999;
$gray4 : #bbbbbb;
$gray5 : #eeeeee;
$gray6 : #f5f5f5;
$gray7 : #f7f7f7;
$gray8 : #cccccc;
$gray9 : #dadada;
$gray10 : #dddddd;

$LineActiveBG : #dbf6fa;

$font92 : 92px;
$font88 : 88px;
$font72 : 72px;
$font64 : 64px;
$font58 : 58px;
$font56 : 56px;
$font48 : 48px;
$font46 : 46px;
$font42 : 42px;
$font40 : 40px;
$font38 : 38px;
$font36 : 36px;
$font34 : 34px;
$font32 : 32px;
$font30 : 32px;
$font28 : 30px;
$font26 : 28px;
$font24 : 26px;
$font20 : 22px;
$font16 : 16px;

**Comment by kalidasya** [comment]
@chanjetsdp this is not valid css, the css plugin does not support any dynamic css language like sass postcss scss
