### ISSUE TITLE
Add support for Less

### ISSUE THREAD

**Issue by racodond** [SonarQubeCommunity/sonar-css#276]

**Comment by kalidasya** [comment]
@racodond the reason why I never worked too much on finishing the less parser (or was it sass?) it is still not clear what is the most popular one, less, sass, scss, now postcss, stylus... any idea?

**Comment by racodond** [comment]
@kalidasya I'll start to work on supporting Less because it's a language one of my clients is using extensively. And it's pretty widely used elsewehere. Once I've added, the support for Less, I'll try to figure out which languages are the most used and I'll also ask on the mailing list which languages the community would like to be supported.

**Comment by kalidasya** [comment]
@racodond sounds good, good luck! I had troubles with switching parsers based on the extension from one plugin back then, I guess it is still lying there unanswered in the google groups

**Comment by racodond** [comment]
@kalidasya Thanks! I'm currently moving to strongly typed AST. That should also help adding support of Less on top of CSS. I'll see but for sure, it won't be a piece of cake :-)

**Comment by kalidasya** [comment]
@racodond wow thats interesting, I tried to update the erlang plugin to the latest plugin api based on your update on css, it was not simple already... strongly typed ast seemed a big chunk of work

**Comment by racodond** [comment]
@kalidasya 

> I tried to update the erlang plugin to the latest plugin api based on your update on css, it was not simple already... 

Did you manage to update?

> strongly typed ast seemed a big chunk of work

It took me a while to figure out the concepts and the code. But it's quite interesting. It will also provide the ability to create custom rules. I already spent a tremendous amount of days but still some work remaining :-)

**Comment by kalidasya** [comment]
@racodond no I gave up, I do not have much time to work on it, I hope I can pick it up sometime later.

ok that is what I was expecting :) , really looking forward to see the changes

**Comment by racodond** [comment]
Moved to https://github.com/racodond/sonar-css-plugin/issues/6
