### ISSUE TITLE
Identify incorrect grammar with multiple declarations without semicolon

### ISSUE THREAD

**Issue by kalidasya** [SonarQubeCommunity/sonar-css#51]
Css grammar should not parse things like:
a
{ color:red background: none }

**Comment by racodond** [comment]
@kalidasya Let's say that it is syntactically valid, see https://drafts.csswg.org/css-syntax-3/#any-value. So, let's the plugin parse it.

Note that rule `validate-property-value` will raise an issue because value `red background: none` is not valid for property `color`.
